# -*- coding: utf-8 -*-
"""HTML Quick-Styler

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YRElSfyqOfWl38vo_yF-pcpARTGhVbrw
"""

!pip install gradio
!pip install transformers
!pip install accelerate
!pip install torch

from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "ibm-granite/granite-3.3-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

print("Model Loaded Successfully")

def generate_html(title, description):

    html = f"""
    <html>
    <head>
    <title>{title}</title>
    <style>
    body {{
        font-family: Arial;
        margin: 40px;
    }}

    h1 {{
        color: #6366f1;
    }}
    </style>
    </head>

    <body>

    <h1>{title}</h1>
    <p>{description}</p>

    </body>
    </html>
    """

    return html

import gradio as gr

def create_page(title, description):
    return generate_html(title, description)

app = gr.Interface(
    fn=create_page,
    inputs=["text", "text"],
    outputs="html",
    title="HTML Quick Styler"
)

app.launch(share=True)

